# Generated by Django 4.0.3 on 2022-04-02 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('A', 'OPCION A'), ('B', 'OPCION B'), ('C', 'OPCION C'), ('D', 'OPCION D')], max_length=1)),
                ('placed', models.CharField(choices=[('Colombia', 'Colombia'), ('Argentina', 'Argentina'), ('Brasil', 'Brasil'), ('Chile', 'Chile')], max_length=20)),
                ('details', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_item', to='login_reg_app.user')),
            ],
        ),
    ]
