# Generated by Django 3.2.10 on 2022-04-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla33_app', '0002_auto_20211215_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('A', 'OPCION A'), ('B', 'OPCION B'), ('C', 'OPCION C'), ('D', 'OPCION D')], max_length=1),
        ),
    ]
