# Generated by Django 3.2.10 on 2022-04-01 19:52

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla33_app', '0003_auto_20220401_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_place', to='plantilla33_app.device')),
            ],
        ),
    ]
