# Generated by Django 3.2.10 on 2022-04-01 20:11

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla33_app', '0004_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
