# Generated by Django 3.2.10 on 2022-04-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla33_app', '0005_auto_20220401_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='city',
        ),
        migrations.RemoveField(
            model_name='device',
            name='location',
        ),
    ]
