# Generated by Django 3.2.10 on 2022-04-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla33_app', '0007_alter_device_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='sensor_type',
            field=models.CharField(choices=[('Temperatura', 'Temperatura')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='details',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='device',
            name='placed',
            field=models.CharField(choices=[('Colombia', 'Colombia'), ('Argentina', 'Argentina'), ('Brasil', 'Brasil'), ('Chile', 'Chile')], max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('Arduino', 'Arduino'), ('Raspberry', 'Raspberry'), ('ESP8266', 'ESP8266'), ('ESP32', 'ESP32')], max_length=20),
        ),
    ]
