# Generated by Django 3.2.10 on 2022-04-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla33_app', '0008_auto_20220402_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='imageDevice',
            field=models.ImageField(blank=True, upload_to='<django.db.models.fields.CharField>Image/'),
        ),
    ]
