# Generated by Django 3.2.10 on 2022-04-03 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla33_app', '0009_device_imagedevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='sensor_type',
        ),
    ]
