# Generated by Django 3.2.10 on 2022-04-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla33_app', '0010_remove_device_sensor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='imageDevice',
            field=models.ImageField(blank=True, upload_to='ImageDevices/'),
        ),
    ]
