# Generated by Django 4.0.3 on 2022-04-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla33_app', '0016_device_device_id_alter_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='imageDevice',
            field=models.FileField(blank=True, upload_to='devices/'),
        ),
    ]
